version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"  # Correctly formatted as an array of strings
    environment:
      - DATABASE_URL=mysql+pymysql://root:2001@mysql:3306/testdb
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 2001
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"  # Correctly formatted as an array of strings
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
